@extends('layout.master')

@push('plugin-styles')
  <link href="{{ asset('build/plugins/flatpickr/flatpickr.min.css') }}" rel="stylesheet" />
@endpush

@section('content')
<div class="d-flex justify-content-between align-items-center flex-wrap grid-margin gap-3">
  <div>
    <h4 class="mb-1">{{ $miner->name }} Overview</h4>
    <p class="text-secondary mb-0">Track live production, share pricing, miner capacity, and overall package performance.</p>
  </div>
  <div class="d-flex gap-2 flex-wrap">
    <a href="{{ route('dashboard.buy-shares') }}?miner={{ $miner->slug }}" class="btn btn-primary btn-sm">Buy shares</a>
    <a href="{{ route('dashboard.profile') }}" class="btn btn-outline-primary btn-sm">Personal profile</a>
  </div>
</div>

@if (($miners ?? collect())->count() > 1)
  <div class="row mb-4">
    <div class="col-12">
      <div class="card">
        <div class="card-body d-flex justify-content-between align-items-center flex-wrap gap-3">
          <div>
            <h6 class="mb-1">Miner switcher</h6>
            <p class="text-secondary mb-0">Compare all available mining units and review each one separately.</p>
          </div>
          <div class="d-flex flex-wrap gap-2">
            @foreach ($miners as $networkMiner)
              <a href="{{ route('dashboard') }}?miner={{ $networkMiner->slug }}" class="btn {{ $networkMiner->id === $miner->id ? 'btn-primary' : 'btn-outline-primary' }} btn-sm">
                {{ $networkMiner->name }}
              </a>
            @endforeach
          </div>
        </div>
      </div>
    </div>
  </div>
@endif

<div class="row">
  <div class="col-md-3 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="text-secondary mb-1">Daily output</p>
        <h3 class="mb-2">${{ number_format((float) $miner->daily_output_usd, 2) }}</h3>
        <div class="d-flex align-items-center gap-2 text-success">
          <i data-lucide="activity" class="icon-sm"></i>
          <span>{{ number_format((float) collect($performanceUptimeData)->last(), 2) }}% uptime today</span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="text-secondary mb-1">Share price</p>
        <h3 class="mb-2">${{ number_format((float) $miner->share_price, 2) }}</h3>
        <div class="text-secondary small">Base monthly return: {{ number_format((float) $miner->base_monthly_return_rate * 100, 2) }}%</div>
      </div>
    </div>
  </div>
  <div class="col-md-3 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="text-secondary mb-1">Shares available</p>
        <h3 class="mb-2">{{ number_format($availableShares) }} / {{ number_format($miner->total_shares) }}</h3>
        <div class="progress" style="height: 8px;">
          <div class="progress-bar bg-primary" role="progressbar" style="width: {{ $miner->total_shares > 0 ? min(($sharesSold / $miner->total_shares) * 100, 100) : 0 }}%"></div>
        </div>
        <div class="text-secondary small mt-2">{{ number_format($sharesSold) }} shares sold</div>
      </div>
    </div>
  </div>
  <div class="col-md-3 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="text-secondary mb-1">Monthly output</p>
        <h3 class="mb-2">${{ number_format((float) $miner->monthly_output_usd, 2) }}</h3>
        <div class="text-secondary small">Active packages: {{ $miner->packages->count() }}</div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xl-8 grid-margin stretch-card">
    <div class="card overflow-hidden">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-baseline mb-3 flex-wrap gap-2">
          <div>
            <h6 class="card-title mb-1">{{ $miner->name }} production trend</h6>
            <p class="text-secondary mb-0">Last 7 days of miner revenue generated by the selected unit.</p>
          </div>
          <a href="{{ route('dashboard.miner') }}?miner={{ $miner->slug }}" class="btn btn-outline-primary btn-sm">Open miner details</a>
        </div>
        <div id="minerRevenueChart"></div>
      </div>
    </div>
  </div>
  <div class="col-xl-4 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h6 class="card-title mb-3">Miner summary</h6>
        <div class="mb-3">
          <div class="text-secondary small">Miner name</div>
          <div class="fs-5 fw-semibold">{{ $miner->name }}</div>
        </div>
        <div class="mb-3">
          <div class="text-secondary small">Status</div>
          <div class="fs-6 fw-semibold text-capitalize">{{ $miner->status }}</div>
        </div>
        <div class="mb-3">
          <div class="text-secondary small">Total capacity</div>
          <div class="fs-5 fw-semibold">{{ number_format($miner->total_shares) }} shares</div>
        </div>
        <div class="mb-3">
          <div class="text-secondary small">Sold capacity</div>
          <div class="fs-5 fw-semibold">{{ number_format($sharesSold) }} shares</div>
        </div>
        <div>
          <div class="text-secondary small">Utilization</div>
          <div class="fs-5 fw-semibold">{{ $miner->total_shares > 0 ? number_format(min(($sharesSold / $miner->total_shares) * 100, 100), 2) : '0.00' }}%</div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h6 class="card-title mb-3">Miner stats</h6>
        <div id="minerStatsChart"></div>
      </div>
    </div>
  </div>
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-baseline mb-3 flex-wrap gap-2">
          <h6 class="card-title mb-0">Package highlights</h6>
          <a href="{{ route('dashboard.buy-shares') }}?miner={{ $miner->slug }}" class="btn btn-outline-success btn-sm">View packages</a>
        </div>
        <div class="table-responsive">
          <table class="table table-borderless mb-0">
            <tbody>
              @forelse ($miner->packages as $package)
                <tr>
                  <td class="ps-0">
                    <div class="fw-semibold">{{ $package->name }}</div>
                    <div class="text-secondary small">{{ $package->shares_count }} shares included</div>
                  </td>
                  <td class="text-end">
                    <div class="fw-semibold">${{ number_format((float) $package->price, 2) }}</div>
                    <div class="text-secondary small">{{ number_format((float) $package->monthly_return_rate * 100, 2) }}% monthly return</div>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="2" class="ps-0 text-secondary">No active packages are assigned to this miner yet.</td>
                </tr>
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2">
          <div>
            <h6 class="card-title mb-1">Recent performance logs</h6>
            <p class="text-secondary mb-0">A quick client-facing snapshot of the miner's most recent recorded performance.</p>
          </div>
          <a href="{{ route('dashboard.miner') }}?miner={{ $miner->slug }}" class="btn btn-outline-primary btn-sm">Open full miner page</a>
        </div>
        <div class="table-responsive">
          <table class="table table-hover align-middle mb-0">
            <thead>
              <tr>
                <th>Date</th>
                <th>Revenue</th>
                <th>Hashrate</th>
                <th>Uptime</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($recentPerformanceLogs as $log)
                <tr>
                  <td>{{ $log->logged_on?->format('M d, Y') }}</td>
                  <td>${{ number_format((float) $log->revenue_usd, 2) }}</td>
                  <td>{{ number_format((float) $log->hashrate_th, 2) }} TH/s</td>
                  <td>{{ number_format((float) $log->uptime_percentage, 2) }}%</td>
                </tr>
              @empty
                <tr>
                  <td colspan="4" class="text-secondary">No performance logs are available yet for this miner.</td>
                </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <div class="alert alert-light border mt-3 mb-0">
          This overview stays focused on miner-wide information. Personal investment and referral details live in your profile page, while the full technical/admin controls stay in the Miner page.
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('plugin-scripts')
  <script src="{{ asset('build/plugins/flatpickr/flatpickr.min.js') }}"></script>
  <script src="{{ asset('build/plugins/apexcharts/apexcharts.min.js') }}"></script>
@endpush

@push('custom-scripts')
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      if (!window.ApexCharts) {
        return;
      }

      const revenueElement = document.querySelector('#minerRevenueChart');
      if (revenueElement) {
        new ApexCharts(revenueElement, {
          chart: {
            type: 'area',
            height: 320,
            toolbar: { show: false }
          },
          series: [{
            name: 'Revenue (USD)',
            data: @json($performanceRevenueData)
          }],
          xaxis: {
            categories: @json($performanceLabels)
          },
          stroke: {
            curve: 'smooth',
            width: 3
          },
          dataLabels: { enabled: false },
          colors: ['#6571ff'],
          fill: {
            type: 'gradient',
            gradient: {
              opacityFrom: 0.35,
              opacityTo: 0.05
            }
          }
        }).render();
      }

      const statsElement = document.querySelector('#minerStatsChart');
      if (statsElement) {
        new ApexCharts(statsElement, {
          chart: {
            type: 'line',
            height: 320,
            toolbar: { show: false }
          },
          series: [
            {
              name: 'Hashrate (TH/s)',
              data: @json($performanceHashrateData)
            },
            {
              name: 'Uptime %',
              data: @json($performanceUptimeData)
            }
          ],
          xaxis: {
            categories: @json($performanceLabels)
          },
          stroke: {
            curve: 'smooth',
            width: 3
          },
          dataLabels: { enabled: false },
          colors: ['#00acc1', '#05a34a']
        }).render();
      }
    });
  </script>
@endpush



